Portfolio/Models/ErrorViewModel.cs
namespace Portfolio.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Portfolio/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Portfolio.Models;
using System.Diagnostics;

namespace Portfolio.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Portfolio/Controllers/LandingController.cs
using Microsoft.AspNetCore.Mvc;

namespace Portfolio.Controllers
{
    public class LandingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Portfolio/Controllers/ResumeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Portfolio.Controllers
{
    public class ResumeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

Portfolio/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="carousel-inner">

        <div class="carousel-item active">
            <div class="view">

            <div id="main-img"><img src="~/images/main.jpeg" width="100%" height="100%" style="position: relative; bottom: 130px; right: 50px"></div>

            <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

                <div class="text-center text-white mx-5">
                    <h1 class="mb-4">
                        <strong>Hi, welcome to my page!</strong>
                    </h1>

                    <p class="mb-4 d-none d-md-block">
                        <strong>
                            Feel free to walk around and visit my LinkedIn!
                        </strong>
                    </p>

                    <a target="_blank" href="https://www.linkedin.com/in/angelo-macapinlac-73a352137/" class="btn btn-outline-white btn-lg">
                        LinkedIn
                        <i class="fa-brands fa-linkedin"></i>
                    </a>
                </div>

            </div>

        </div>
    </div>
</div>
<main>
    <div id="content" class="container">

        <section class="mt-5">

            <div class="row">

                <div class="col-md-6 mb-4" style="text-align:center">

                    <img src="/images/image-1.jpeg" width="300px" height="400px" class="img-fluid z-depth-1-half" alt="">

                </div>
                <div class="col-md-6 mb-4">
                    <h3 class="h3 mb-3">I am Angelo Macapinlac</h3>
                    <p>
                        An aspiring Software Developer with 5+ years of experience
                    </p>
                    <hr>
                    <p>
                        Graduate of BS in Information System from
                        <strong>Technological University of the Philippines - Manila</strong>
                    </p>

                    <a target="_blank" href="https://www.facebook.com/gelosenpaii/" class="btn btn-grey btn-md">
                        Facebook
                        <i class="fa-brands fa-facebook"></i>
                    </a>

                </div>

            </div>

        </section>

        <hr class="my-5">

        <section>

            <h3 class="h3 text-center mb-5">Skills</h3>

            <div class="row">

                <div class="col-lg-6 col-md-12 px-4">
                    <div class="row fade item">
                        <div class="col-1 mr-3">
                            <i class="fa-solid fa-2x fa-gears"></i>
                        </div>
                        <div class="col-10">
                            <h5 class="feature-title">.NET Core Technology</h5>
                            <p class="grey-text">Use of the latest .Net Technology for building applications</p>
                        </div>
                    </div>

                    <div style="height:30px"></div>

                    <div class="row fade item">
                        <div class="col-1 mr-3">
                            <i class="fa-solid fa-2x fa-code"></i>
                        </div>
                        <div class="col-10">
                            <h5 class="feature-title">C# ASP.NET MVC</h5>
                            <p class="grey-text">
                                Framework for developing web application and APIs along with the use of Model-View-Controller architectural pattern
                            </p>
                        </div>
                    </div>

                    <div style="height:30px"></div>

                    <div class="row fade item">
                        <div class="col-1 mr-3">
                            <i class="fa-solid fa-2x fa-database"></i>
                        </div>
                        <div class="col-10">
                            <h5 class="feature-title">Oracle Database</h5>
                            <p class="grey-text">
                                Database management with the use of PL/SQL stored procedures
                            </p>
                        </div>
                    </div>

                </div>
                <div class="col-lg-6 col-md-12 px-4">
                    <div class="row fade item">
                        <div class="col-1 mr-3">
                            <i class="fa-solid fa-2x fa-server"></i>
                        </div>
                        <div class="col-10">
                            <h5 class="feature-title">SQL Server</h5>
                            <p class="grey-text">
                                For application data storage
                            </p>
                        </div>
                    </div>
                    <div class="row fade item">
                        <div class="col-1 mr-3">
                            <i class="fa-solid fa-2x fa-file-code"></i>
                        </div>
                        <div class="col-10">
                            <h5 class="feature-title">Object-Oriented Programming</h5>
                            <p class="grey-text">
                                Strong knowledge in OOP structure
                            </p>
                        </div>
                    </div>
                </div>

            </div>

        </section>

        <hr class="my-5">

        <section>
            <h2 class="my-5 h3 text-center">Work Experience</h2>

            <div class="row mb-5 mt-3">

                <div class="col-sm">
                    <div class="row js-slidein">
                        <div class="col-2">
                            <i class="fas fa-check-circle fa-2x indigo-text"></i>
                        </div>
                        <div class="col-10">
                            <h6 class="feature-title"><strong>Amellar Solutions</strong></h6>
                            <p class="grey-text" style="margin-bottom: 0">
                                San, Juan City
                            </p>
                            <p class="grey-text" style="margin-bottom: 0">
                                2017 - 2022
                            </p>
                            <p class="grey-text">
                                Software Developer
                            </p>
                            <div style="height:15px"></div>
                        </div>
                    </div>
                    <div class="row js-slidein">
                        <div class="col-2">
                            <i class="fas fa-check-circle fa-2x indigo-text"></i>
                        </div>
                        <div class="col-10">
                            <h6 class="feature-title"><strong>H2 Software Consulting Services, Inc.</strong></h6>
                            <p class="grey-text" style="margin-bottom: 0">
                                Pasig City
                            </p>
                            <p class="grey-text" style="margin-bottom: 0">
                                2022 - Present
                            </p>
                            <p class="grey-text">
                                C# .Net Core Developer
                            </p>
                            <div style="height:15px"></div>
                        </div>
                    </div>
                    <div class="row js-slidein">
                        <div class="col-2">
                            <i class="fas fa-check-circle fa-2x indigo-text"></i>
                        </div>
                        <div class="col-10">
                            <h6 class="feature-title"><strong>CTBC Bank (Philippines) Corp. - Client</strong></h6>
                            <p class="grey-text" style="margin-bottom: 0">
                                Taguig, City
                            </p>
                            <p class="grey-text" style="margin-bottom: 0">
                                2022 - Present
                            </p>
                            <p class="grey-text">
                                C# .Net Core Developer
                            </p>
                            <div style="height:15px"></div>
                        </div>
                    </div>

                </div>
                <div class="col-sm js-slidein">
                    <img src="/images/work-pic.jpg" class="z-depth-0 img-fluid">
                </div>
            </div>

        </section>

        <hr class="mb-5">

        <section>

            <h2 class="my-5 h3 text-center">Accomplishments</h2>

            <div class="row features-small mt-5 wow fadeIn">

                <div class="col-xl-3 col-lg-6">
                    <div class="row fade item">
                        <div class="col-2">
                            <i class="fa-solid fa-building fa-2x mb-1 indigo-text" aria-hidden="true"></i>
                        </div>
                        <div class="col-10 mb-2 pl-3">
                            <h5 class="feature-title font-bold mb-1">Engineering Permit System</h5>
                            <p class="grey-text mt-2">
                                Developed and engineered Local Government engineering permit application system
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6">
                    <div class="row fade item">
                        <div class="col-2">
                            <i class="fa-solid fa-briefcase fa-2x mb-1 indigo-text" aria-hidden="true"></i>
                        </div>
                        <div class="col-10 mb-2">
                            <h5 class="feature-title font-bold mb-1">Business Application System</h5>
                            <p class="grey-text mt-2">
                                Engineered business licensing system of multiple LGUs
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6">
                    <div class="row fade item">
                        <div class="col-2">
                            <i class="fa-solid fa-money-bill-transfer fa-2x mb-1 indigo-text" aria-hidden="true"></i>
                        </div>
                        <div class="col-10 mb-2">
                            <h5 class="feature-title font-bold mb-1">LGU Financial Management System</h5>
                            <p class="grey-text mt-2">
                                Developed and maintained financial management system of Roxas, Isabela LGU
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6">
                    <div class="row fade item">
                        <div class="col-2">
                            <i class="fa-solid fa-file-invoice fa-2x mb-1 indigo-text" aria-hidden="true"></i>
                        </div>
                        <div class="col-10 mb-2">
                            <h5 class="feature-title font-bold mb-1">Bank charging system</h5>
                            <p class="grey-text mt-2">
                                Enhanced legacy charging system of client bank
                            </p>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row features-small mt-4">

                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="row fade item">
                        <div class="col-2">
                            <i class="fa-solid fa-people-line fa-2x mb-1 indigo-text" aria-hidden="true"></i>
                        </div>
                        <div class="col-10 mb-2">
                            <h5 class="feature-title font-bold mb-1">Corporate banking payroll system</h5>
                            <p class="grey-text mt-2">
                                Developed and enhanced legacy payroll system of client bank.
                            </p>
                        </div>
                    </div>
                </div>

            </div>

        </section>
    </div>
</main>

Portfolio/Views/Landing/Index.cshtml
@{
    Layout = "~/Views/Shared/_LandingLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="profile-card-2">
                <img src="~/images/jes.jpeg" class="img img-responsive" width="100%" height="100%">
                <div class="profile-name">JESBER ADAO</div>
                <div class="profile-username">Software Developer</div>
                <div class="profile-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a></div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="profile-card-2">
                <img src="~/images/image-1.jpeg" class="img img-responsive" width="100%" height="100%">
                <div class="profile-name">ANGELO MACAPINLAC</div>
                <div class="profile-username">Software Developer</div>
                <div class="profile-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a></div>
            </div>
        </div>
    </div>
</div>

Portfolio/Views/Resume/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="resumeContainer">
    <embed id="resumepdf" src="~/images/Angelo-Macapinlac.pdf" width="500" height="375"
           type="application/pdf">
</div>

Portfolio/Views/Shared/_LandingLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Jes & Gelo - Portfolio</title>
    <link rel="stylesheet" href="~/mdb-ui-kit/mdb.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/slidein.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/spinner.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/landing.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Portfolio.styles.css" asp-append-version="true" />
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/mdb-ui-kit/mdb.min.js"></script>
    <script src="~/font-awesome/js/all.js"></script>
    <script src="~/js/fadin.js"></script>
    <script src="~/js/slidein.js"></script>
    <script src="~/simple-parallax-js/simpleParallax.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Portfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Angelo Macapinlac - Portfolio</title>
    @*<link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/mdb-ui-kit/mdb.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/slidein.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Portfolio.styles.css" asp-append-version="true" />
</head>
<body>
    <div>
        <nav id="navbar" class="navbar justify-content-center navbar-expand-lg navbar-dark scrolling-navbar">
            <div class="container justify-content-center">
                <ul class="navbar-nav nav-flex-icons align-items-center">
                    <li class="nav-item navAround">
                        <a href="https://www.facebook.com/gelosenpaii/" style="color: black"
                           target="_blank">
                            <i class="fa-brands fa-facebook" style="color: black;"></i> Facebook
                        </a>
                    </li>
                    <li class="nav-item navAround">
                        <a href="https://github.com/legopaisen" style="color: black"
                            target="_blank">
                            <i class="fab fa-github mr-2" style="color: black;"></i> GitHub
                        </a>
                    </li>
                    <li class="nav-item navMiddle">
                        <a class="navbar-brand" href="@Url.Action("Index","Home")" target="_self">
                            <img src="~/images/signature.png" height="58px" width="200px"/>
                        </a>
                    </li>
                    <li class="nav-item navAround">
                        <a href="https://www.linkedin.com/in/angelo-macapinlac-73a352137/"" style="color: black"
                            target="_blank">
                            <i class="fa-brands fa-linkedin" style="color: black;"></i> LinkedIn
                        </a>
                    </li>
                    <li class="nav-item navAround">
                        <a href="@Url.Action("Index","Resume")" " style="color: black"
                           target="_blank">
                            <i class="fa-solid fa-file-lines" style="color: black;"></i> Resume
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        @RenderBody()
    </div>

    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/mdb-ui-kit/mdb.min.js"></script>
    <script src="~/font-awesome/js/all.js"></script>
    <script src="~/js/fadin.js"></script>
    <script src="~/js/slidein.js"></script>
    <script src="~/simple-parallax-js/simpleParallax.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    <script>
        //$(document).ready(function(){
        //    $(window).on("scroll", function () {
        //        var content = document.getElementById("content");
        //        // Get the offset position of the navbar
        //        var sticky = content.offsetTop;
        //        var navbar = document.getElementById("navbar");
        //        myFunction(content, sticky, navbar);

        //    });


        //});

        //function myFunction(content, sticky, navbar) {
        //    if (window.pageYOffset >= sticky) {
        //        navbar.classList.add("sticky")
        //    } 
        //    else {
        //        navbar.classList.remove("sticky");
        //    }
        //}
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>